### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/assets/bootstrap/<module_name>.js.map")

### ISSUE THREAD

**Issue by Gedrovits** [twbs/bootstrap-rubygem#12]
When the *bootstrap-sprockets* used in application.js file, it throws this errors for each of JS modules.

Example error message:
```
ActionController::RoutingError (No route matches [GET] "/assets/bootstrap/util.js.map"):
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  rack-mini-profiler (0.9.7) lib/mini_profiler/profiler.rb:170:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  thin (1.6.4) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.4) lib/thin/connection.rb:84:in `catch'
  thin (1.6.4) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.4) lib/thin/connection.rb:53:in `process'
  thin (1.6.4) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.8) lib/eventmachine.rb:193:in `run_machine'
  eventmachine (1.0.8) lib/eventmachine.rb:193:in `run'
  thin (1.6.4) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.4) lib/thin/server.rb:162:in `start'
  rack (1.6.4) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.4) lib/rack/server.rb:286:in `start'
  railties (4.2.4) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.4) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.4) lib/rails/commands/commands_tasks.rb:75:in `tap'
  railties (4.2.4) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.4) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.4) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `require'
  bin/rails:4:in `<top (required)>'
  -e:1:in `load'
  -e:1:in `<main>'
```

The JS seems to work and load, but those errors being throwed.

If the *bootstrap* used in application.js, then there is no errors in the console.

**Comment by glebm** [comment]
I cannot reproduce this. What versions of sprockets and sprockets-rails are you using?

**Comment by Gedrovits** [comment]
@glebm OK, it seems the problem not in gem itself, but in the Chrome...

If you open Chrome Development Tools and refresh the page, you will receive the errors I provided.
Technically this is not gem bug, so can be closed freely.

**Comment by alexdunae** [comment]
There's a `sourceMappingURL` directive at the end of each of the included JS files (e.g. https://github.com/twbs/bootstrap-rubygem/blob/master/assets/javascripts/bootstrap/util.js#L157) that's causing this.

Maybe those could be stripped out by updater/js.rb (since the .map) files aren't included in the gem?

**Comment by glebm** [comment]
@alexdunae Good catch, we need to strip these :+1:

**Comment by alexdunae** [comment]
Nice -- thank you.
