### ISSUE TITLE
Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by Zapotek** [twbs/bootstrap-rubygem#192]
Hello, just by installing `gem 'bootstrap', '~> 4.4.0'` (previous version `gem 'bootstrap-sass', '3.3.6'`) I'm getting the following error:

```
Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8
/home/user/.rvm/gems/ruby-2.7.1@project/gems/execjs-2.7.0/lib/execjs/encoding.rb:22:in `encode'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/execjs-2.7.0/lib/execjs/encoding.rb:22:in `encode'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:8:in `initialize'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `new'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `compile'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/execjs-2.7.0/lib/execjs/module.rb:27:in `compile'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/autoprefixer-rails-9.7.6/lib/autoprefixer-rails/processor.rb:160:in `runtime'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/autoprefixer-rails-9.7.6/lib/autoprefixer-rails/processor.rb:36:in `process'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/autoprefixer-rails-9.7.6/lib/autoprefixer-rails/sprockets.rb:20:in `run'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/autoprefixer-rails-9.7.6/lib/autoprefixer-rails/sprockets.rb:14:in `call'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:84:in `call_processor'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `reverse_each'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `call_processors'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/loader.rb:182:in `load_from_unloaded'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/loader.rb:59:in `block in load'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/loader.rb:43:in `load'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/cached_environment.rb:44:in `load'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/bundle.rb:32:in `block in call'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/bundle.rb:31:in `call'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:84:in `call_processor'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `reverse_each'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/processor_utils.rb:65:in `call_processors'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/loader.rb:182:in `load_from_unloaded'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/loader.rb:59:in `block in load'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/loader.rb:43:in `load'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/cached_environment.rb:44:in `load'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/base.rb:81:in `find_asset'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/base.rb:88:in `find_all_linked_assets'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/sprockets-4.0.2/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/concurrent-ruby-1.0.5/lib/concurrent/promise.rb:531:in `block in realize'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/user/.rvm/gems/ruby-2.7.1@project/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

manifest.js:

```
//= link application.css
//= link application.js
```

If I remove `//= link application.css` the error goes away, but if I empty the `application.css.scss` file the error remains.

**Comment by arielkirkwood** [comment]
Is it possible you may have used “smart quotes”? When I see this kind of error in Ruby my mind goes to the kind of characters that may not exist in ASCII but are still easy to type in some environments.
