### ISSUE TITLE
Issue with bundle exec rake 'update[v5.2.0-beta1]'

### ISSUE THREAD

**Issue by danielvlopes** [twbs/bootstrap-rubygem#232]
Hey there,

Since Bootstrap updated the docs to 5.2.0-beta1, I was trying to get the gem to update the source to this new beta, but it looks like we'll need to make some changes to the `updater/js.rb` file for it work with the new JS files. I'm not exactly sure why there's a difference between the inline source and the others, so I'm hesitant to change the code and send a PR before asking here. If you could provide any guidance here, I'd be happy to make the changes myself.

The following is the full trace I'm getting (everything goes well with CSS and crashes on the JS part).

Thank you very much in advance.

```
❯ bundle exec rake 'update[v5.2.0-beta1]'
git ls-remote https://github.com/twbs/bootstrap v5.2.0-beta1
Updating Bootstrap
 repo   : https://github.com/twbs/bootstrap
 branch : fca04c07131a81e625a516cf7b98a8c7df0df1c1 https://github.com/twbs/bootstrap/tree/v5.2.0-beta1
 save to: {"js":"assets/javascripts/bootstrap","scss":"assets/stylesheets/bootstrap"}
 twbs cache: tmp/bootstrap-cache
------------------------------------------------------------
Updating scss...
  CACHED GET https://api.github.com/repos/twbs/bootstrap/git/trees/fca04c07131a81e625a516cf7b98a8c7df0df1c1?recursive=1...
  CACHED GET https://api.github.com/repos/twbs/bootstrap/git/trees/3478d210c5ed422ad6813b1a3762f76db9335bb7?recursive=1...
  CACHED GET 87 files from https://raw.githubusercontent.com/twbs/bootstrap/fca04c07131a81e625a516cf7b98a8c7df0df1c1/scss _accordion.scss _alert.scss _badge.scss _breadcrumb.scss _button-group.scss _buttons.scss _card.scss _carousel.scss _close.scss _containers.scss _dropdown.scss _forms.scss _functions.scss _grid.scss _helpers.scss _images.scss _list-group.scss _maps.scss _mixins.scss _modal.scss _nav.scss _navbar.scss _offcanvas.scss _pagination.scss _placeholders.scss _popover.scss _progress.scss _reboot.scss _root.scss _spinners.scss _tables.scss _toasts.scss _tooltip.scss _transitions.scss _type.scss _utilities.scss _variables.scss bootstrap-grid.scss bootstrap-reboot.scss bootstrap-utilities.scss bootstrap.scss forms/_floating-labels.scss forms/_form-check.scss forms/_form-control.scss forms/_form-range.scss forms/_form-select.scss forms/_form-text.scss forms/_input-group.scss forms/_labels.scss forms/_validation.scss helpers/_clearfix.scss helpers/_color-bg.scss helpers/_colored-links.scss helpers/_position.scss helpers/_ratio.scss helpers/_stacks.scss helpers/_stretched-link.scss helpers/_text-truncation.scss helpers/_visually-hidden.scss helpers/_vr.scss mixins/_alert.scss mixins/_backdrop.scss mixins/_border-radius.scss mixins/_box-shadow.scss mixins/_breakpoints.scss mixins/_buttons.scss mixins/_caret.scss mixins/_clearfix.scss mixins/_color-scheme.scss mixins/_container.scss mixins/_deprecate.scss mixins/_forms.scss mixins/_gradients.scss mixins/_grid.scss mixins/_image.scss mixins/_list-group.scss mixins/_lists.scss mixins/_pagination.scss mixins/_reset-text.scss mixins/_resize.scss mixins/_table-variants.scss mixins/_text-truncate.scss mixins/_transition.scss mixins/_utilities.scss mixins/_visually-hidden.scss utilities/_api.scss vendor/_rfs.scss...
    _accordion.scss _alert.scss _badge.scss _breadcrumb.scss _button-group.scss _buttons.scss _card.scss _carousel.scss _close.scss _containers.scss _dropdown.scss _forms.scss _functions.scss _grid.scss _helpers.scss _images.scss _list-group.scss _maps.scss _mixins.scss _modal.scss _nav.scss _navbar.scss _offcanvas.scss _pagination.scss _placeholders.scss _popover.scss _progress.scss _reboot.scss _root.scss _spinners.scss _tables.scss _toasts.scss _tooltip.scss _transitions.scss _type.scss _utilities.scss _variables.scss bootstrap-grid.scss bootstrap-reboot.scss bootstrap-utilities.scss bootstrap.scss forms/_floating-labels.scss forms/_form-check.scss forms/_form-control.scss forms/_form-range.scss forms/_form-select.scss forms/_form-text.scss forms/_input-group.scss forms/_labels.scss forms/_validation.scss helpers/_clearfix.scss helpers/_color-bg.scss helpers/_colored-links.scss helpers/_position.scss helpers/_ratio.scss helpers/_stacks.scss helpers/_stretched-link.scss helpers/_text-truncation.scss helpers/_visually-hidden.scss helpers/_vr.scss mixins/_alert.scss mixins/_backdrop.scss mixins/_border-radius.scss mixins/_box-shadow.scss mixins/_breakpoints.scss mixins/_buttons.scss mixins/_caret.scss mixins/_clearfix.scss mixins/_color-scheme.scss mixins/_container.scss mixins/_deprecate.scss mixins/_forms.scss mixins/_gradients.scss mixins/_grid.scss mixins/_image.scss mixins/_list-group.scss mixins/_lists.scss mixins/_pagination.scss mixins/_reset-text.scss mixins/_resize.scss mixins/_table-variants.scss mixins/_text-truncate.scss mixins/_transition.scss mixins/_utilities.scss mixins/_visually-hidden.scss utilities/_api.scss vendor/_rfs.scss
Updating scss main files
Updating javascripts...
  CACHED GET https://api.github.com/repos/twbs/bootstrap/git/trees/4edfa3aecfa1caf749200562f109d21474e9ad66?recursive=1...
src_files: ["alert.js", "base-component.js", "button.js", "carousel.js", "collapse.js", "dom/data.js", "dom/event-handler.js", "dom/manipulator.js", "dom/selector-engine.js", "dropdown.js", "modal.js", "offcanvas.js", "popover.js", "scrollspy.js", "tab.js", "toast.js", "tooltip.js", "util/config.js", "util/swipe.js", "util/template-factory.js"]
  CACHED GET 20 files from https://raw.githubusercontent.com/twbs/bootstrap/fca04c07131a81e625a516cf7b98a8c7df0df1c1/js/src alert.js base-component.js button.js carousel.js collapse.js dom/data.js dom/event-handler.js dom/manipulator.js dom/selector-engine.js dropdown.js modal.js offcanvas.js popover.js scrollspy.js tab.js toast.js tooltip.js util/config.js util/swipe.js util/template-factory.js...
rake aborted!
No imports found for "index.js"
/Users/daniel/Development/projects/bootstrap-rubygem/tasks/updater/js.rb:77:in `tsort_each_child'
/Users/daniel/Development/projects/bootstrap-rubygem/tasks/updater/js.rb:79:in `each'
/Users/daniel/Development/projects/bootstrap-rubygem/tasks/updater/js.rb:79:in `tsort_each_child'
/Users/daniel/Development/projects/bootstrap-rubygem/tasks/updater/js.rb:79:in `each'
/Users/daniel/Development/projects/bootstrap-rubygem/tasks/updater/js.rb:79:in `tsort_each_child'
/Users/daniel/Development/projects/bootstrap-rubygem/tasks/updater/js.rb:79:in `each'
/Users/daniel/Development/projects/bootstrap-rubygem/tasks/updater/js.rb:79:in `tsort_each_child'
/Users/daniel/Development/projects/bootstrap-rubygem/tasks/updater/js.rb:83:in `each_key'
/Users/daniel/Development/projects/bootstrap-rubygem/tasks/updater/js.rb:83:in `tsort_each_node'
/Users/daniel/Development/projects/bootstrap-rubygem/tasks/updater/js.rb:55:in `bootstrap_js_files'
/Users/daniel/Development/projects/bootstrap-rubygem/tasks/updater/js.rb:10:in `update_javascript_assets'
/Users/daniel/Development/projects/bootstrap-rubygem/tasks/updater.rb:47:in `update_bootstrap'
/Users/daniel/Development/projects/bootstrap-rubygem/Rakefile:66:in `block in <top (required)>'
/Users/daniel/.asdf/installs/ruby/2.7.2/bin/bundle:23:in `load'
/Users/daniel/.asdf/installs/ruby/2.7.2/bin/bundle:23:in `<main>'
Tasks: TOP => update
(See full trace by running task with --trace)
```

**Comment by glebm** [comment]
The files that are inlined by the compiler need to be listed here:

https://github.com/twbs/bootstrap-rubygem/blob/9892831e005bdb2da72f41aa42a6391baa6ad188/tasks/updater/js.rb#L5

**Comment by glebm** [comment]
5.2.0 and 5.2.1 are released
