### ISSUE TITLE
Provide build for 5.3.0-alpha1

### ISSUE THREAD

**Issue by idbentley** [twbs/bootstrap-rubygem#249]
I tried to make the build myself by running `rake "update[v5.3.0-alpha1]"` but ran into some issues building it on my environment.

```
..snip
src_files: ["alert.js", "base-component.js", "button.js", "carousel.js", "collapse.js", "dom/data.js", "dom/event-handler.js", "dom/manipulator.js", "dom/selector-engine.js", "dropdown.js", "modal.js", "offcanvas.js", "popover.js", "scrollspy.js", "tab.js", "toast.js", "tooltip.js", "util/backdrop.js", "util/component-functions.js", "util/config.js", "util/focustrap.js", "util/index.js", "util/sanitizer.js", "util/scrollbar.js", "util/swipe.js", "util/template-factory.js"]
  GET 26 files from https://raw.githubusercontent.com/twbs/bootstrap/cf9454caa00872899215603e5e036d9a824b1b11/js/src alert.js base-component.js button.js carousel.js collapse.js dom/data.js dom/event-handler.js dom/manipulator.js dom/selector-engine.js dropdown.js modal.js offcanvas.js popover.js scrollspy.js tab.js toast.js tooltip.js util/backdrop.js util/component-functions.js util/config.js util/focustrap.js util/index.js util/sanitizer.js util/scrollbar.js util/swipe.js util/template-factory.js...
rake aborted!
No imports found for "util/index.js.js"
Imports:
{"dom/data.js"=>[], "dom/selector-engine.js"=>["util/index.js.js"], "base-component.js"=>["dom/data.js.js", "dom/event-handler.js.js", "util/config.js.js", "util/index.js.js"], "dropdown.js"=>["base-component.js.js", "dom/event-handler.js.js", "dom/manipulator.js.js", "dom/selector-engine.js.js"], "popover.js"=>["tooltip.js.js", "util/index.js.js"], "offcanvas.js"=>["base-component.js.js", "dom/event-handler.js.js", "dom/selector-engine.js.js", "util/backdrop.js.js", "util/component-functions.js.js", "util/focustrap.js.js", "util/scrollbar.js.js"], "toast.js"=>["base-component.js.js", "dom/event-handler.js.js", "util/component-functions.js.js", "util/index.js.js"], "modal.js"=>["base-component.js.js", "dom/event-handler.js.js", "dom/selector-engine.js.js", "util/backdrop.js.js", "util/component-functions.js.js", "util/focustrap.js.js", "util/index.js.js", "util/scrollbar.js.js"], "carousel.js"=>["base-component.js.js", "dom/event-handler.js.js", "dom/manipulator.js.js", "dom/selector-engine.js.js", "util/swipe.js.js"], "util/focustrap.js"=>["dom/event-handler.js.js", "dom/selector-engine.js.js", "util/config.js.js"], "util/scrollbar.js"=>["dom/manipulator.js.js", "dom/selector-engine.js.js", "util/index.js.js"], "util/template-factory.js"=>["dom/selector-engine.js.js", "util/config.js.js", "util/index.js.js", "util/sanitizer.js.js"], "alert.js"=>["base-component.js.js", "dom/event-handler.js.js", "util/component-functions.js.js", "util/index.js.js"], "scrollspy.js"=>["base-component.js.js", "dom/event-handler.js.js", "dom/selector-engine.js.js", "util/index.js.js"], "collapse.js"=>["base-component.js.js", "dom/event-handler.js.js", "dom/selector-engine.js.js"], "tooltip.js"=>["base-component.js.js", "dom/event-handler.js.js", "dom/manipulator.js.js", "util/index.js.js", "util/sanitizer.js.js", "util/template-factory.js.js"], "util/sanitizer.js"=>[], "button.js"=>["base-component.js.js", "dom/event-handler.js.js", "util/index.js.js"], "util/config.js"=>["dom/manipulator.js.js", "util/index.js.js"], "dom/manipulator.js"=>[], "dom/event-handler.js"=>["util/index.js.js"], "util/component-functions.js"=>["dom/event-handler.js.js", "dom/selector-engine.js.js", "util/index.js.js"], "util/swipe.js"=>["dom/event-handler.js.js", "util/config.js.js", "util/index.js.js"], "tab.js"=>["base-component.js.js", "dom/event-handler.js.js", "dom/selector-engine.js.js", "util/index.js.js"], "util/index.js"=>[], "util/backdrop.js"=>["dom/event-handler.js.js", "util/config.js.js", "util/index.js.js"]}
/home/ian/development/bootstrap-rubygem-2/tasks/updater/js.rb:82:in `tsort_each_child'
/home/ian/development/bootstrap-rubygem-2/tasks/updater/js.rb:84:in `each'
/home/ian/development/bootstrap-rubygem-2/tasks/updater/js.rb:84:in `tsort_each_child'
/home/ian/development/bootstrap-rubygem-2/tasks/updater/js.rb:88:in `each_key'
/home/ian/development/bootstrap-rubygem-2/tasks/updater/js.rb:88:in `tsort_each_node'
/home/ian/development/bootstrap-rubygem-2/tasks/updater/js.rb:58:in `bootstrap_js_files'
/home/ian/development/bootstrap-rubygem-2/tasks/updater/js.rb:11:in `update_javascript_assets'
/home/ian/development/bootstrap-rubygem-2/tasks/updater.rb:47:in `update_bootstrap'
/home/ian/development/bootstrap-rubygem-2/Rakefile:66:in `block in <top (required)>'
Tasks: TOP => update
(See full trace by running task with --trace)
```

Could you please provide a build of the new version, at your convenience?

**Comment by anywherepilot** [comment]
All the file names end in `.js.js`. In `tasks/updater/js.rb:54` changing `join("#{f}.js")` to just `join(f)` makes it work.

**Comment by idbentley** [comment]
Thanks - that worked for me.

**Comment by idbentley** [comment]
By the way, the best practice for ruby gems is to use the preprelease pattern for alpha and beta releases:

https://guides.rubygems.org/patterns/#prerelease-gems

That would be great for those of us living on the edge. :)

**Comment by XhmikosR** [comment]
https://github.com/twbs/bootstrap-rubygem/releases/tag/v5.3.0.alpha3
