### ISSUE TITLE
Update rake task fails

### ISSUE THREAD

**Issue by jcoyne** [twbs/bootstrap-rubygem#66]
```
$ rake update[v4.0.0-alpha.6]
git ls-remote https://github.com/twbs/bootstrap v4.0.0-alpha.6
Updating Bootstrap
 repo   : https://github.com/twbs/bootstrap
 branch : 65ffb1c3b6e94440812a2e228cb8e8be512652ec https://github.com/twbs/bootstrap/tree/v4.0.0-alpha.6
 save to: {"js":"assets/javascripts/bootstrap","scss":"assets/stylesheets/bootstrap"}
 twbs cache: tmp/bootstrap-cache
------------------------------------------------------------
Updating scss...
  GET https://api.github.com/repos/twbs/bootstrap/git/trees/65ffb1c3b6e94440812a2e228cb8e8be512652ec?recursive=1...
  GET https://api.github.com/repos/twbs/bootstrap/git/trees/df5724cb6d7d0e8b24a6f90f0f6f25a477eb37f5?recursive=1...
  GET 82 files from https://raw.githubusercontent.com/twbs/bootstrap/65ffb1c3b6e94440812a2e228cb8e8be512652ec/scss _alert.scss _badge.scss _breadcrumb.scss _button-group.scss _buttons.scss _card.scss _carousel.scss _close.scss _code.scss _custom-forms.scss _custom.scss _dropdown.scss _forms.scss _grid.scss _images.scss _input-group.scss _jumbotron.scss _list-group.scss _media.scss _mixins.scss _modal.scss _nav.scss _navbar.scss _normalize.scss _pagination.scss _popover.scss _print.scss _progress.scss _reboot.scss _responsive-embed.scss _tables.scss _tooltip.scss _transitions.scss _type.scss _utilities.scss _variables.scss bootstrap-grid.scss bootstrap-reboot.scss bootstrap.scss mixins/_alert.scss mixins/_background-variant.scss mixins/_badge.scss mixins/_border-radius.scss mixins/_breakpoints.scss mixins/_buttons.scss mixins/_cards.scss mixins/_clearfix.scss mixins/_float.scss mixins/_forms.scss mixins/_gradients.scss mixins/_grid-framework.scss mixins/_grid.scss mixins/_hover.scss mixins/_image.scss mixins/_list-group.scss mixins/_lists.scss mixins/_nav-divider.scss mixins/_navbar-align.scss mixins/_pagination.scss mixins/_reset-text.scss mixins/_resize.scss mixins/_screen-reader.scss mixins/_size.scss mixins/_table-row.scss mixins/_text-emphasis.scss mixins/_text-hide.scss mixins/_text-truncate.scss mixins/_transforms.scss mixins/_visibility.scss utilities/_align.scss utilities/_background.scss utilities/_borders.scss utilities/_clearfix.scss utilities/_display.scss utilities/_flex.scss utilities/_float.scss utilities/_position.scss utilities/_screenreaders.scss utilities/_sizing.scss utilities/_spacing.scss utilities/_text.scss utilities/_visibility.scss...
    _alert.scss _badge.scss _breadcrumb.scss _button-group.scss _buttons.scss _card.scss _carousel.scss _close.scss _code.scss _custom-forms.scss _custom.scss _dropdown.scss _forms.scss _grid.scss _images.scss _input-group.scss _jumbotron.scss _list-group.scss _media.scss _mixins.scss _modal.scss _nav.scss _navbar.scss _normalize.scss _pagination.scss _popover.scss _print.scss _progress.scss _reboot.scss _responsive-embed.scss _tables.scss _tooltip.scss _transitions.scss _type.scss _utilities.scss _variables.scss bootstrap-grid.scss bootstrap-reboot.scss bootstrap.scss mixins/_alert.scss mixins/_background-variant.scss mixins/_badge.scss mixins/_border-radius.scss mixins/_breakpoints.scss mixins/_buttons.scss mixins/_cards.scss mixins/_clearfix.scss mixins/_float.scss mixins/_forms.scss mixins/_gradients.scss mixins/_grid-framework.scss mixins/_grid.scss mixins/_hover.scss mixins/_image.scss mixins/_list-group.scss mixins/_lists.scss mixins/_nav-divider.scss mixins/_navbar-align.scss mixins/_pagination.scss mixins/_reset-text.scss mixins/_resize.scss mixins/_screen-reader.scss mixins/_size.scss mixins/_table-row.scss mixins/_text-emphasis.scss mixins/_text-hide.scss mixins/_text-truncate.scss mixins/_transforms.scss mixins/_visibility.scss utilities/_align.scss utilities/_background.scss utilities/_borders.scss utilities/_clearfix.scss utilities/_display.scss utilities/_flex.scss utilities/_float.scss utilities/_position.scss utilities/_screenreaders.scss utilities/_sizing.scss utilities/_spacing.scss utilities/_text.scss utilities/_visibility.scss
Updating scss main files
rake aborted!
Errno::ENOENT: No such file or directory @ rb_file_s_rename - (assets/stylesheets/bootstrap/bootstrap-flex.scss, assets/stylesheets/bootstrap/../_bootstrap-flex.scss)
/Users/jcoyne/workspace/bootstrap-rubygem/tasks/updater/scss.rb:20:in `block in update_scss_assets'
/Users/jcoyne/workspace/bootstrap-rubygem/tasks/updater/scss.rb:15:in `each'
/Users/jcoyne/workspace/bootstrap-rubygem/tasks/updater/scss.rb:15:in `update_scss_assets'
/Users/jcoyne/workspace/bootstrap-rubygem/tasks/updater.rb:46:in `update_bootstrap'
/Users/jcoyne/workspace/bootstrap-rubygem/Rakefile:64:in `block in <top (required)>'
Tasks: TOP => update
(See full trace by running task with --trace)
```

**Comment by jcoyne** [comment]
This should be fixed by #64
