### ISSUE TITLE
No longer updatable

### ISSUE THREAD

**Issue by Odaeus** [twbs/bootstrap-rubygem#82]
I have a local copy of the gem I keep up to date with the latest Bootstrap v4 dev branch by running `rake update[v4-dev]` every so often.

Unfortunately this is now broken due to [big changes to the build system](https://github.com/twbs/bootstrap/commit/b4ac48fdec7637c0c7c69f9d3ff9fc5d21d23676):
```
➜  bootstrap-rubygem git:(v4-dev) ✗ rake update[v4-dev]
git ls-remote https://github.com/twbs/bootstrap v4-dev
Updating Bootstrap
 repo   : https://github.com/twbs/bootstrap
[...]
Updating javascripts...
  CACHED GET https://raw.githubusercontent.com/twbs/bootstrap/aa68ca3580369de035742768c64498686a6600ff/Gruntfile.js...
rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
/home/andrew/src/bootstrap-rubygem/tasks/updater/js.rb:36:in `bootstrap_js_files'
/home/andrew/src/bootstrap-rubygem/tasks/updater/js.rb:7:in `update_javascript_assets'
/home/andrew/src/bootstrap-rubygem/tasks/updater.rb:47:in `update_bootstrap'
/home/andrew/src/bootstrap-rubygem/Rakefile:64:in `block in <top (required)>'
Tasks: TOP => update
```

The update method uses some gnarly regex parsing of the Grunfile.js, but that's completely changed now and I'm not sure where I would even start to fix this.

**Comment by Odaeus** [comment]
🙇 Thanks
